version: '3.4'

name: mobile-ecommerce
services:
  mobile-ecommerce:
    image: mobile-ecommerce
    container_name: ecommerce
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ".env"
    ports:
      - 3000:3000